### ISSUE TITLE
Hard-coded to localhost:8080

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/skej#4]
Hi Austin

The value for this for me is in orchestrating remote OpenFaaS instances. Having an override would be useful if you could do that. I'd like to use it for some testing. 

Alex

**Comment by austinfrey** [comment]
Yup it's on the todo list!

**Comment by austinfrey** [comment]
take a look at #6 ? would that do what you need?

**Comment by OmgImAlexis** [comment]
Closed in #6
